use std::collections::{HashMap, HashSet};

use serde::Serialize;

// These are the known browsers from matamo's device detector. While this
// representation is not optimal, I picked this format because it is the easiest format
// to make use of it while having any hope of keeping it up to date with changes upstream.

pub struct AvailableBrowsers {
    // TODO this may not ever be needed.
    //    browsers_by_short: HashMap<String, AvailableBrowser>,
    browsers_by_name: HashMap<String, AvailableBrowser>,
}

#[derive(Clone, Debug, Serialize)]
pub struct AvailableBrowser {
    pub name: String,
    pub family: Option<String>,
    #[serde(skip)]
    pub(crate) mobile_only: bool,
}

impl Default for AvailableBrowsers {
    fn default() -> Self {
        let available_browsers = available_browsers();
        let mobile_only_browsers = mobile_only_browsers();
        let browser_families = browser_families()
            .into_iter()
            .flat_map(|(k, shorts)| {
                let k = &k;
                shorts
                    .into_iter()
                    .map(move |short| (short, k.clone()))
                    .collect::<Vec<(String, String)>>()
            })
            .collect::<HashMap<String, String>>();

        let browsers_by_short = available_browsers
            .into_iter()
            .map(|(short, browser)| {
                let mobile_only = mobile_only_browsers.contains(&short);
                let family = browser_families.get(&short).cloned();
                (
                    short,
                    AvailableBrowser {
                        name: browser,
                        mobile_only,
                        family,
                    },
                )
            })
            .collect::<HashMap<String, AvailableBrowser>>();

        let browsers_by_name = browsers_by_short
            .values()
            .map(|browser| {
                (
                    browser.name.replace(' ', "").to_lowercase(),
                    browser.clone(),
                )
            })
            .collect::<HashMap<String, AvailableBrowser>>();

        Self {
            //browsers_by_short,
            browsers_by_name,
        }
    }
}

impl AvailableBrowsers {
    pub fn search_by_name(&self, name: &str) -> Option<&AvailableBrowser> {
        let name = name.to_lowercase().replace(' ', "");
        self.browsers_by_name
            .get(&name)
            .or_else(|| {
                let mut name = name.clone();
                name.push_str("browser");
                self.browsers_by_name.get(&name)
            })
            .or_else(|| {
                self.browsers_by_name
                    .get(name.to_lowercase().trim_end_matches("browser"))
            })
    }
}

fn available_browsers() -> HashMap<String, String> {
    [
        ("00", "Ace"),
        ("0A", "AppTec Secure Browser"),
        ("0C", "Cave Browser"),
        ("0I", "Ifbrowser"),
        ("0P", "Peach Browser"),
        ("0S", "Sunflower Browser"),
        ("18", "18+ Privacy Browser"),
        ("1A", "Anka Browser"),
        ("1B", "115 Browser"),
        ("1C", "Cake Browser"),
        ("1D", "Dragon Browser"),
        ("1E", "Easy Browser"),
        ("1F", "Firefox Klar"),
        ("1I", "IE Browser Fast"),
        ("1L", "Lightning Browser"),
        ("1M", "1DM+ Browser"),
        ("1N", "ONIONBrowser"),
        ("1O", "OH Browser"),
        ("1P", "Pure Mini Browser"),
        ("1R", "Raise Fast Browser"),
        ("1S", "Sharkee Browser"),
        ("1T", "Tor Browser"),
        ("1V", "Vegas Browser"),
        ("1W", "World Browser"),
        ("1X", "XBrowser Mini"),
        ("2A", "Aplix"),
        ("2B", "2345 Browser"),
        ("2C", "Comfort Browser"),
        ("2E", "Pocket Internet Explorer"),
        ("2F", "ProxyFox"),
        ("2I", "Impervious Browser"),
        ("2L", "Lark Browser"),
        ("2M", "ProxyMax"),
        ("2N", "Neuro Browser"),
        ("2O", "Odin Browser"),
        ("2P", "Puffin Web Browser"),
        ("2S", "Soul Browser"),
        ("2X", "SX Browser"),
        ("36", "360 Phone Browser"),
        ("3A", "AOL Explorer"),
        ("3B", "360 Secure Browser"),
        ("3C", "Chowbo"),
        ("3F", "FireSend Browser"),
        ("3I", "Intune Managed Browser"),
        ("3L", "Samsung Browser Lite"),
        ("3M", "Mises"),
        ("3N", "Nintendo Browser"),
        ("3O", "OH Private Browser"),
        ("3P", "Pluma"),
        ("3S", "SilverMob US"),
        ("3W", "w3m"),
        ("4A", "Acoo Browser"),
        ("4B", "BrowsBit"),
        ("4C", "Colom Browser"),
        ("4I", "iNet Browser"),
        ("4O", "Owl Browser"),
        ("4P", "Pure Lite Browser"),
        ("4S", "Surf Browser"),
        ("4U", "Open Browser 4U"),
        ("5A", "Stealth Browser"),
        ("5B", "Basic Web Browser"),
        ("5C", "Catalyst"),
        ("5G", "Open Browser fast 5G"),
        ("5I", "Internet Webbrowser"),
        ("5O", "Open Browser Lite"),
        ("5P", "Photon"),
        ("5S", "SuperFast Browser"),
        ("6A", "Arachne"),
        ("6B", "Bluefy"),
        ("6C", "Columbus Browser"),
        ("6I", "Puffin Incognito Browser"),
        ("6O", "Opera Air"),
        ("6P", "Proxynet"),
        ("6S", "Smart Search & Web Browser"),
        ("7A", "Awesomium"),
        ("7B", "7654 Browser"),
        ("7C", "Classilla"),
        ("7I", "Puffin Cloud Browser"),
        ("7P", "Proxyium"),
        ("7S", "7Star"),
        ("8A", "Ai Browser"),
        ("8B", "SlimBoat"),
        ("8C", "Cromite"),
        ("8P", "Prism"),
        ("8S", "Secure Private Browser"),
        ("9A", "AltiBrowser"),
        ("9B", "BizBrowser"),
        ("9C", "Clear TV Browser"),
        ("9P", "Presearch"),
        ("9S", "Sony Small Browser"),
        ("A0", "Atom"),
        ("A1", "AwoX"),
        ("A2", "Atlas"),
        ("A3", "Amaze Browser"),
        ("A4", "AOL Shield Pro"),
        ("A5", "Amerigo"),
        ("A6", "AppBrowzer"),
        ("A7", "Adult Browser"),
        ("A8", "ALVA"),
        ("A9", "Airfind Secure Browser"),
        ("AA", "Avant Browser"),
        ("AB", "ABrowse"),
        ("AC", "Avira Secure Browser"),
        ("AD", "AOL Shield"),
        ("AE", "AOL Desktop"),
        ("AF", "ANT Fresco"),
        ("AG", "ANTGalio"),
        ("AH", "Aloha Browser Lite"),
        ("AI", "Arvin"),
        ("AK", "Ask.com"),
        ("AL", "Aloha Browser"),
        ("AM", "Amaya"),
        ("AN", "Android Browser"),
        ("AO", "Amigo"),
        ("AP", "APUS Browser"),
        ("AQ", "ArtisBrowser"),
        ("AR", "Arora"),
        ("AS", "Avast Secure Browser"),
        ("AT", "Atomic Web Browser"),
        ("AU", "Asus Browser"),
        ("AV", "Amiga Voyager"),
        ("AW", "Amiga Aweb"),
        ("AX", "Arctic Fox"),
        ("AY", "Anonyv Browser"),
        ("AZ", "Azka Browser"),
        ("B0", "Bloket"),
        ("B1", "Spectre Browser"),
        ("B2", "Berry Browser"),
        ("B3", "Browspeed Browser"),
        ("B4", "BXE Browser"),
        ("B5", "Beyond Private Browser"),
        ("B6", "Black Lion Browser"),
        ("B7", "Browlser"),
        ("B8", "Browser Hup Pro"),
        ("B9", "Bangla Browser"),
        ("BA", "Beaker Browser"),
        ("BB", "BlackBerry Browser"),
        ("BC", "Black Browser"),
        ("BD", "Baidu Browser"),
        ("BE", "Beonex"),
        ("BF", "Byffox"),
        ("BG", "Bang"),
        ("BH", "BlackHawk"),
        ("BI", "Basilisk"),
        ("BJ", "Bunjalloo"),
        ("BK", "BriskBard"),
        ("BL", "B-Line"),
        ("BM", "Beamrise"),
        ("BN", "Borealis Navigator"),
        ("BO", "Bonsai"),
        ("BP", "Privacy Browser"),
        ("BQ", "Browse Safe"),
        ("BR", "Brave"),
        ("BS", "Baidu Spark"),
        ("BT", "Bitchute Browser"),
        ("BU", "Blue Browser"),
        ("BV", "Belva Browser"),
        ("BW", "AdBlock Browser"),
        ("BX", "BrowseX"),
        ("BY", "Biyubi"),
        ("BZ", "Browzar"),
        ("C0", "Centaury"),
        ("C1", "Coast"),
        ("C2", "Colibri"),
        ("C3", "Chim Lac"),
        ("C4", "CoolBrowser"),
        ("C5", "Chromium GOST"),
        ("C6", "Chedot"),
        ("C7", "CM Mini"),
        ("C8", "CG Browser"),
        ("C9", "Cherry Browser"),
        ("CA", "Camino"),
        ("CB", "COS Browser"),
        ("CC", "Coc Coc"),
        ("CD", "Comodo Dragon"),
        ("CE", "CM Browser"),
        ("CF", "Chrome Frame"),
        ("CG", "Craving Explorer"),
        ("CH", "Chrome"),
        ("CI", "Chrome Mobile iOS"),
        ("CJ", "ChanjetCloud"),
        ("CK", "Conkeror"),
        ("CL", "CCleaner"),
        ("CM", "Chrome Mobile"),
        ("CN", "CoolNovo"),
        ("CO", "CometBird"),
        ("CP", "ChromePlus"),
        ("CQ", "Cliqz"),
        ("CR", "Chromium"),
        ("CS", "Cheshire"),
        ("CT", "Crusta"),
        ("CU", "Cunaguaro"),
        ("CV", "Chrome Webview"),
        ("CW", "Cornowser"),
        ("CX", "Charon"),
        ("CY", "Cyberfox"),
        ("CZ", "Crazy Browser"),
        ("D0", "Desi Browser"),
        ("D1", "Debuggable Browser"),
        ("D2", "DoCoMo"),
        ("D3", "Dezor"),
        ("D4", "DDU Browser"),
        ("D6", "Dark Browser"),
        ("D8", "Doubao"),
        ("DA", "Deledao"),
        ("DB", "dbrowser"),
        ("DC", "Decentr"),
        ("DD", "DuckDuckGo Privacy Browser"),
        ("DE", "Deepnet Explorer"),
        ("DF", "Dolphin"),
        ("DG", "deg-degan"),
        ("DI", "Dillo"),
        ("DK", "Dark Web"),
        ("DL", "Dooble"),
        ("DM", "1DM Browser"),
        ("DO", "Dorado"),
        ("DP", "Dark Web Private"),
        ("DR", "Dot Browser"),
        ("DS", "DeskBrowse"),
        ("DT", "Delta Browser"),
        ("DU", "DUC Browser"),
        ("DW", "Dark Web Browser"),
        ("DZ", "Dolphin Zero"),
        ("E1", "East Browser"),
        ("E2", "EudoraWeb"),
        ("EB", "Element Browser"),
        ("EC", "Ecosia"),
        ("EE", "Elements Browser"),
        ("EI", "Epic"),
        ("EL", "Elinks"),
        ("EN", "EinkBro"),
        ("EO", "Eolie"),
        ("EP", "GNOME Web"),
        ("ES", "Espial TV Browser"),
        ("EU", "EUI Browser"),
        ("EV", "Every Browser"),
        ("EW", "Edge WebView"),
        ("EX", "Explore Browser"),
        ("EZ", "eZ Browser"),
        ("F0", "Float Browser"),
        ("F1", "Firefox Mobile iOS"),
        ("F2", "Flow Browser"),
        ("F3", "Frost+"),
        ("F4", "Fiery Browser"),
        ("F5", "Flyperlink"),
        ("F6", "Freedom Browser"),
        ("F7", "BF Browser"),
        ("F8", "Fire Browser"),
        ("F9", "FOSS Browser"),
        ("FA", "Falkon"),
        ("FB", "Firebird"),
        ("FD", "Fluid"),
        ("FE", "Fennec"),
        ("FF", "Firefox"),
        ("FG", "fGet"),
        ("FH", "Flash Browser"),
        ("FI", "Fulldive"),
        ("FJ", "Fast Explorer"),
        ("FK", "Firefox Focus"),
        ("FL", "Flock"),
        ("FM", "Firefox Mobile"),
        ("FN", "Fireweb Navigator"),
        ("FO", "Flow"),
        ("FP", "Floorp"),
        ("FQ", "Fast Browser UC Lite"),
        ("FR", "Firefox Rocket"),
        ("FS", "Flast"),
        ("FT", "Frost"),
        ("FU", "FreeU"),
        ("FW", "Fireweb"),
        ("FX", "Faux Browser"),
        ("FY", "Firefox Reality"),
        ("G0", "ChatGPT Atlas"),
        ("G1", "G Browser"),
        ("G2", "GO Browser"),
        ("G3", "Good Browser"),
        ("G8", "Gener8"),
        ("GA", "Galeon"),
        ("GB", "Glass Browser"),
        ("GD", "Godzilla Browser"),
        ("GE", "Google Earth"),
        ("GH", "Ghostery Privacy Browser"),
        ("GI", "GinxDroid Browser"),
        ("GK", "GoKu"),
        ("GN", "Legan Browser"),
        ("GO", "GOG Galaxy"),
        ("GP", "Google Earth Pro"),
        ("GR", "GoBrowser"),
        ("H1", "BrowseHere"),
        ("H2", "OceanHero"),
        ("H3", "HUB Browser"),
        ("H4", "Holla Web Browser"),
        ("H5", "HotBrowser"),
        ("H6", "HONOR Browser"),
        ("H7", "Halo Browser"),
        ("H8", "HeyTapBrowser"),
        ("HA", "Hawk Turbo Browser"),
        ("HB", "Harman Browser"),
        ("HC", "Headless Chrome"),
        ("HE", "Helio"),
        ("HH", "OhHai Browser"),
        ("HI", "Hi Browser"),
        ("HJ", "HotJava"),
        ("HM", "Harmony 360 Browser"),
        ("HN", "Herond Browser"),
        ("HO", "hola! Browser"),
        ("HP", "Huawei Browser"),
        ("HQ", "Hawk Quick Browser"),
        ("HR", "Sushi Browser"),
        ("HS", "HasBrowser"),
        ("HT", "HTC Browser"),
        ("HU", "Huawei Browser Mobile"),
        ("HW", "Habit Browser"),
        ("HX", "Hexa Web Browser"),
        ("I1", "Iridium"),
        ("I2", "iCab Mobile"),
        ("I3", "Iron Mobile"),
        ("I4", "IceCat"),
        ("I5", "Indian UC Mini Browser"),
        ("I6", "iDesktop PC Browser"),
        ("I7", "Internet Browser Secure"),
        ("I8", "IVVI Browser"),
        ("I9", "Insta Browser"),
        ("IB", "IBrowse"),
        ("IC", "iCab"),
        ("ID", "IceDragon"),
        ("IE", "Internet Explorer"),
        ("IF", "Lolifox"),
        ("IG", "Involta Go"),
        ("II", "Diigo Browser"),
        ("IM", "IE Mobile"),
        ("IN", "Inspect Browser"),
        ("IO", "iBrowser"),
        ("IR", "Iron"),
        ("IS", "iBrowser Mini"),
        ("IV", "Isivioo"),
        ("IW", "Iceweasel"),
        ("JA", "JavaFX"),
        ("JB", "Japan Browser"),
        ("JI", "Jig Browser"),
        ("JL", "Jelly"),
        ("JO", "JioSphere"),
        ("JP", "Jig Browser Plus"),
        ("JR", "OJR Browser"),
        ("JS", "Jasmine"),
        ("JZ", "JUZI Browser"),
        ("K1", "Sidekick"),
        ("K2", "BroKeep Browser"),
        ("K3", "Skye"),
        ("K4", "Kitt"),
        ("K5", "Spark"),
        ("K6", "Perk"),
        ("K7", "KeepSolid Browser"),
        ("KA", "Ask Browser"),
        ("KB", "K.Browser"),
        ("KD", "Kode Browser"),
        ("KE", "Keyboard Browser"),
        ("KF", "Keepsafe Browser"),
        ("KI", "Kindle Browser"),
        ("KJ", "K-Ninja"),
        ("KK", "SiteKiosk"),
        ("KL", "SkyLeap"),
        ("KM", "K-meleon"),
        ("KN", "Kinza"),
        ("KO", "Konqueror"),
        ("KP", "Kapiko"),
        ("KS", "Kids Safe Browser"),
        ("KT", "KUTO Mini Browser"),
        ("KU", "KUN"),
        ("KW", "Kiwi"),
        ("KY", "Kylo"),
        ("KZ", "Kazehakase"),
        ("L1", "Lilo"),
        ("L2", "Lynket Browser"),
        ("L3", "Lotus"),
        ("L4", "Lightning Browser Plus"),
        ("LA", "Lagatos Browser"),
        ("LB", "Cheetah Browser"),
        ("LC", "LogicUI TV Browser"),
        ("LD", "Ladybird"),
        ("LE", "Smart Lenovo Browser"),
        ("LF", "LieBaoFast"),
        ("LG", "LG Browser"),
        ("LH", "Light"),
        ("LI", "Links"),
        ("LJ", "LUJO TV Browser"),
        ("LL", "Lulumi"),
        ("LM", "Lemur Browser"),
        ("LN", "Lunascape Lite"),
        ("LO", "Lovense Browser"),
        ("LR", "Lexi Browser"),
        ("LS", "Lunascape"),
        ("LT", "LT Browser"),
        ("LU", "LuaKit"),
        ("LV", "Lenovo Browser"),
        ("LX", "Lynx"),
        ("LY", "PolyBrowser"),
        ("M1", "mCent"),
        ("M2", "Me Browser"),
        ("M3", "Midori Lite"),
        ("M4", "MaxTube Browser"),
        ("M5", "MarsLab Web Browser"),
        ("M6", "MixerBox AI"),
        ("M7", "MaxBrowser"),
        ("M8", "Motorola Internet Browser"),
        ("M9", "Browser Mini"),
        ("MA", "Maelstrom"),
        ("MB", "MicroB"),
        ("MC", "NCSA Mosaic"),
        ("MD", "Mandarin"),
        ("ME", "Mercury"),
        ("MF", "Mobile Safari"),
        ("MI", "Midori"),
        ("MK", "Mogok Browser"),
        ("MM", "Mmx Browser"),
        ("MN", "Minimo"),
        ("MO", "Mobicip"),
        ("MP", "Maple"),
        ("MR", "Monument Browser"),
        ("MS", "Mobile Silk"),
        ("MT", "Mint Browser"),
        ("MU", "Mi Browser"),
        ("MW", "MAUI WAP Browser"),
        ("MX", "Maxthon"),
        ("MY", "Mypal"),
        ("MZ", "Meizu Browser"),
        ("N0", "Nova Video Downloader Pro"),
        ("N1", "NOMone VR Browser"),
        ("N2", "Norton Private Browser"),
        ("N3", "Incognito Browser"),
        ("N4", "Onion Browser"),
        ("N5", "Ninetails"),
        ("N6", "Nook Browser"),
        ("N7", "Naenara Browser"),
        ("N8", "Ninesky"),
        ("N9", "Pintar Browser"),
        ("NA", "Naked Browser Pro"),
        ("NB", "Nokia Browser"),
        ("NE", "NetSurf"),
        ("NF", "NetFront"),
        ("NI", "Nuviu"),
        ("NK", "Naked Browser"),
        ("NL", "NetFront Life"),
        ("NM", "MxNitro"),
        ("NO", "Nokia OSS Browser"),
        ("NP", "NetPositive"),
        ("NQ", "Nova Browser"),
        ("NR", "NFS Browser"),
        ("NS", "Netscape"),
        ("NT", "NTENT Browser"),
        ("NU", "Nuanti Meta"),
        ("NV", "Nokia Ovi Browser"),
        ("NW", "Navigateur Web"),
        ("NX", "Nox Browser"),
        ("O0", "Origin In-Game Overlay"),
        ("O1", "Opera Mini iOS"),
        ("O2", "Odin"),
        ("O3", "OpenFin"),
        ("O4", "Open Browser"),
        ("O5", "Office Browser"),
        ("O6", "Odd Browser"),
        ("O7", "Open TV Browser"),
        ("O8", "OrNET Browser"),
        ("O9", "Ocean Browser"),
        ("OA", "Orca"),
        ("OB", "Obigo"),
        ("OC", "Oculus Browser"),
        ("OD", "Odyssey Web Browser"),
        ("OE", "ONE Browser"),
        ("OF", "Off By One"),
        ("OG", "Opera Neon"),
        ("OH", "Opera Devices"),
        ("OI", "Opera Mini"),
        ("OL", "OnBrowser Lite"),
        ("OM", "Opera Mobile"),
        ("ON", "Opera Next"),
        ("OO", "Opera Touch"),
        ("OP", "Opera"),
        ("OR", "Oregano"),
        ("OS", "Ordissimo"),
        ("OT", "Otter Browser"),
        ("OU", "Orbitum"),
        ("OV", "Openwave Mobile Browser"),
        ("OW", "OmniWeb"),
        ("OX", "Opera GX"),
        ("OY", "Origyn Web Browser"),
        ("OZ", "Smooz"),
        ("P0", "PronHub Browser"),
        ("P1", "Phantom.me"),
        ("P2", "Pi Browser"),
        ("P3", "Private Internet Browser"),
        ("P4", "Privacy Explorer Fast Safe"),
        ("P5", "Proxy Browser"),
        ("P6", "Opus Browser"),
        ("P7", "Pawxy"),
        ("P8", "PICO Browser"),
        ("P9", "PirateBrowser"),
        ("PA", "Palmscape"),
        ("PB", "Phoenix Browser"),
        ("PC", "PSI Secure Browser"),
        ("PD", "Peeps dBrowser"),
        ("PE", "Perfect Browser"),
        ("PF", "PlayFree Browser"),
        ("PH", "Phantom Browser"),
        ("PI", "PrivacyWall"),
        ("PK", "PocketBook Browser"),
        ("PL", "Palm Blazer"),
        ("PM", "Pale Moon"),
        ("PN", "APN Browser"),
        ("PO", "Polaris"),
        ("PP", "Oppo Browser"),
        ("PQ", "Power Browser"),
        ("PR", "Palm Pre"),
        ("PS", "Microsoft Edge"),
        ("PT", "Polarity"),
        ("PU", "Puffin Secure Browser"),
        ("PV", "Safari Technology Preview"),
        ("PW", "Palm WebPro"),
        ("PX", "Phoenix"),
        ("PY", "Polypane"),
        ("PZ", "Panda Browser"),
        ("Q1", "QQ Browser Mini"),
        ("Q2", "QQ Browser Lite"),
        ("Q3", "Qmamu"),
        ("Q4", "Quick Search TV"),
        ("Q5", "QtWeb"),
        ("Q6", "QuarkPC"),
        ("Q7", "Quetta"),
        ("QA", "Qazweb"),
        ("QI", "Qiyu"),
        ("QJ", "QJY TV Browser"),
        ("QM", "Qwant Mobile"),
        ("QQ", "QQ Browser"),
        ("QS", "Quick Browser"),
        ("QT", "Qutebrowser"),
        ("QU", "Quark"),
        ("QW", "QtWebEngine"),
        ("QZ", "QupZilla"),
        ("R0", "SberBrowser"),
        ("R1", "Rabbit Private Browser"),
        ("R2", "Raspbian Chromium"),
        ("R3", "Rakuten Browser"),
        ("R4", "Rakuten Web Search"),
        ("R5", "Armorfly Browser"),
        ("R6", "Ray"),
        ("RA", "Arc Search"),
        ("RB", "Roku Browser"),
        ("RC", "Crow Browser"),
        ("RE", "Realme Browser"),
        ("RF", "SOTI Surf"),
        ("RI", "Liri Browser"),
        ("RK", "Rekonq"),
        ("RM", "RockMelt"),
        ("RN", "GreenBrowser"),
        ("RO", "Roccat"),
        ("RT", "RCA Tor Explorer"),
        ("RW", "Reqwireless WebViewer"),
        ("RY", "Surfy Browser"),
        ("S0", "START Internet Browser"),
        ("S1", "SimpleBrowser"),
        ("S2", "Splash"),
        ("S3", "surf"),
        ("S4", "Steam In-Game Overlay"),
        ("S5", "Safe Exam Browser"),
        ("S6", "Slimjet"),
        ("S7", "SP Browser"),
        ("S8", "Seewo Browser"),
        ("S9", "Secure Browser"),
        ("SA", "Sailfish Browser"),
        ("SB", "Samsung Browser"),
        ("SC", "SEMC-Browser"),
        ("SD", "SavySoda"),
        ("SE", "Sogou Explorer"),
        ("SF", "Safari"),
        ("SG", "Stargon"),
        ("SH", "Shiira"),
        ("SI", "Sputnik Browser"),
        ("SJ", "Seekee"),
        ("SK", "Skyfire"),
        ("SL", "Sleipnir"),
        ("SM", "Snap Browser"),
        ("SN", "Snowshoe"),
        ("SO", "Sogou Mobile Browser"),
        ("SP", "SuperBird"),
        ("SQ", "Smart Browser"),
        ("SR", "Sunrise"),
        ("SS", "Seraphic Sraf"),
        ("ST", "Streamy"),
        ("SU", "Super Fast Browser"),
        ("SV", "SFive"),
        ("SW", "SalamWeb"),
        ("SX", "Swiftfox"),
        ("SY", "Sizzy"),
        ("SZ", "Seznam Browser"),
        ("T0", "Soundy Browser"),
        ("T1", "Stampy Browser"),
        ("T2", "tararia"),
        ("T3", "Total Browser"),
        ("T4", "TV-Browser Internet"),
        ("T5", "Tincat Browser"),
        ("TA", "Tao Browser"),
        ("TB", "Tenta Browser"),
        ("TC", "TUC Mini Browser"),
        ("TE", "Tesla Browser"),
        ("TF", "TenFourFox"),
        ("TG", "ToGate"),
        ("TH", "Thor"),
        ("TI", "Tint Browser"),
        ("TK", "TUSK"),
        ("TL", "TrueLocation Browser"),
        ("TO", "t-online.de Browser"),
        ("TP", "T+Browser"),
        ("TQ", "TQ Browser"),
        ("TR", "T-Browser"),
        ("TS", "TweakStyle"),
        ("TT", "TalkTo"),
        ("TU", "Tungsten"),
        ("TV", "TV Bro"),
        ("TZ", "Tizen Browser"),
        ("U0", "U Browser"),
        ("UB", "UBrowser"),
        ("UC", "UC Browser"),
        ("UE", "Ume Browser"),
        ("UH", "UC Browser HD"),
        ("UI", "Ui Browser Mini"),
        ("UM", "UC Browser Mini"),
        ("UP", "UPhone Browser"),
        ("UR", "UR Browser"),
        ("UT", "UC Browser Turbo"),
        ("UZ", "Uzbl"),
        ("V0", "vBrowser"),
        ("V1", "Via"),
        ("V2", "Vivid Browser Mini"),
        ("V3", "VD Browser"),
        ("V4", "Vertex Surf"),
        ("V5", "VibeMate"),
        ("V6", "VMS Mosaic"),
        ("V7", "Vivaldi Mobile iOS"),
        ("VA", "Vast Browser"),
        ("VB", "Vision Mobile Browser"),
        ("VE", "Venus Browser"),
        ("VG", "AVG Secure Browser"),
        ("VI", "Vivaldi"),
        ("VK", "Vonkeror"),
        ("VM", "VMware AirWatch"),
        ("VN", "Savannah Browser"),
        ("VQ", "VC Browser Mini Pro"),
        ("VR", "Veera"),
        ("VS", "Viasat Browser"),
        ("VU", "Vuhuv"),
        ("VV", "vivo Browser"),
        ("W1", "Sweet Browser"),
        ("W2", "Whale TV Browser"),
        ("W3", "Web Browser & Explorer"),
        ("W4", "WebDiscover"),
        ("W5", "Webian Shell"),
        ("W6", "Weltweitimnetz Browser"),
        ("W7", "Swiftweasel"),
        ("WA", "Wavebox"),
        ("WB", "Wave Browser"),
        ("WD", "Vewd Browser"),
        ("WE", "WebPositive"),
        ("WF", "Waterfox"),
        ("WH", "Whale Browser"),
        ("WI", "Wear Internet Browser"),
        ("WK", "Wukong Browser"),
        ("WL", "Wolvic"),
        ("WO", "wOSBrowser"),
        ("WP", "Web Explorer"),
        ("WR", "NextWord Browser"),
        ("WT", "WeTab Browser"),
        ("WX", "Wexond"),
        ("WY", "Wyzo"),
        ("X0", "X-VPN"),
        ("X1", "xBrowser Pro Super Fast"),
        ("X2", "SecureX"),
        ("X3", "MMBOX XBrowser"),
        ("X4", "XnBrowse"),
        ("X5", "Cloak Private Browser"),
        ("X6", "XPlay Browser"),
        ("XB", "X Browser Lite"),
        ("XC", "Comet"),
        ("XI", "Xiino"),
        ("XN", "XNX Browser"),
        ("XO", "Xooloo Internet"),
        ("XP", "Catsxp"),
        ("XR", "xBrowser"),
        ("XS", "xStand"),
        ("XT", "XtremeCast"),
        ("XV", "Xvast"),
        ("Y1", "Opera Crypto"),
        ("Y2", "Yo Browser"),
        ("Y3", "YouBrowser"),
        ("Y4", "Yandex Browser Corp"),
        ("YA", "Yandex Browser"),
        ("YB", "Yolo Browser"),
        ("YC", "CyBrowser"),
        ("YG", "YAGI"),
        ("YJ", "Yahoo! Japan Browser"),
        ("YL", "Yandex Browser Lite"),
        ("YN", "Yaani Browser"),
        ("YO", "YouCare"),
        ("YS", "Stay Browser"),
        ("YZ", "Yuzu Browser"),
        ("Z0", "InBrowser"),
        ("Z1", "Blazer"),
        ("ZB", "Singlebox"),
        ("ZC", "Clario Browser"),
        ("ZE", "Zetakey"),
        ("ZI", "Zirco Browser"),
        ("ZR", "Zordo Browser"),
        ("ZT", "ZTE Browser"),
        ("ZV", "Zvu"),
    ]
    .into_iter()
    .map(|(short, name)| (short.to_owned(), name.to_owned()))
    .collect::<HashMap<String, String>>()
}

fn browser_families() -> HashMap<String, Vec<String>> {
    [
        (
            "Amiga",
            vec![
                "AV", "AW",
            ],
        ),
        (
            "Android Browser",
            vec![
                "AN",
            ],
        ),
        (
            "Baidu",
            vec![
                "BD", "BS", "H6",
            ],
        ),
        (
            "BlackBerry Browser",
            vec![
                "BB",
            ],
        ),
        (
            "Chrome",
            vec![
                "00", "0A", "0C", "0I", "0P", "0S", "18", "1B", "1M", "1N", "1T", "1W", "2B", "2F",
                "2M", "2N", "2P", "2S", "2X", "3F", "3I", "3M", "3P", "4S", "5B", "5O", "6I", "7I",
                "7S", "8A", "8B", "8C", "8S", "9C", "9P", "A0", "A4", "A5", "A6", "A7", "A8", "A9",
                "AC", "AE", "AH", "AI", "AK", "AL", "AO", "AP", "AS", "AY", "AZ", "B0", "B1", "B5",
                "B6", "B8", "B9", "BA", "BC", "BG", "BM", "BO", "BP", "BQ", "BR", "BT", "BV", "BW",
                "C2", "C3", "C4", "C5", "C6", "C8", "CC", "CD", "CE", "CF", "CG", "CH", "CI", "CJ",
                "CL", "CM", "CN", "CP", "CR", "CV", "CW", "D0", "D3", "D4", "D6", "D8", "DA", "DC",
                "DD", "DG", "DM", "DR", "DT", "DU", "E1", "EC", "EE", "EU", "EV", "EW", "F0", "F3",
                "F4", "F5", "F6", "F7", "F9", "FA", "FH", "FS", "FT", "G0", "G2", "G8", "GB", "GD",
                "GI", "GN", "H2", "H3", "H4", "H5", "H7", "H8", "HA", "HB", "HC", "HE", "HH", "HI",
                "HN", "HO", "HP", "HQ", "HR", "HS", "HT", "HU", "I1", "I3", "I9", "IO", "IR", "JB",
                "JO", "JR", "K1", "K2", "K3", "K4", "K5", "K6", "K7", "KA", "KN", "KS", "KW", "L1",
                "LA", "LC", "LF", "LJ", "LL", "LM", "LO", "LR", "LT", "M1", "M5", "M9", "MA", "MD",
                "MM", "MR", "MS", "MT", "MU", "MZ", "N0", "N2", "N3", "N9", "NA", "NM", "NQ", "NR",
                "NX", "O0", "O2", "O3", "O4", "O5", "O6", "O7", "O9", "OC", "OL", "P0", "P1", "P2",
                "P3", "P5", "P7", "P8", "PB", "PC", "PD", "PN", "PQ", "PT", "PU", "PZ", "Q3", "Q4",
                "Q6", "Q7", "QI", "QU", "QW", "R0", "R1", "R2", "R6", "RB", "RC", "RF", "RI", "RM",
                "S4", "S6", "S8", "S9", "SB", "SD", "SG", "SJ", "SM", "SQ", "SS", "SU", "SV", "SW",
                "SY", "SZ", "T0", "T1", "T3", "T4", "T5", "TA", "TB", "TC", "TE", "TG", "TK", "TP",
                "TR", "TS", "TU", "TV", "U0", "UB", "UI", "UR", "V0", "V3", "V4", "V7", "VA", "VE",
                "VG", "VI", "VM", "VN", "VQ", "VR", "VS", "W1", "W2", "W4", "WA", "WB", "WD", "WH",
                "WK", "WP", "WR", "WX", "X0", "X1", "X2", "X3", "X4", "X5", "X6", "XB", "XC", "XN",
                "XO", "XP", "XT", "XV", "YG", "YJ", "YO", "YS", "Z1", "ZB", "ZC", "ZR",
            ],
        ),
        (
            "Firefox",
            vec![
                "2I", "7C", "8P", "AD", "AX", "BF", "BH", "BI", "BN", "C0", "CU", "EI", "F1", "FB",
                "FE", "FF", "FM", "FP", "FR", "FY", "I4", "IF", "IW", "KJ", "LH", "LY", "MB", "MN",
                "MO", "MY", "N7", "OA", "OS", "P9", "PI", "PX", "QA", "S5", "SX", "TF", "TO", "VK",
                "W5", "W7", "WF", "WY", "ZV",
            ],
        ),
        (
            "Internet Explorer",
            vec![
                "2E", "3A", "4A", "BZ", "CZ", "IE", "IM", "PS", "RN",
            ],
        ),
        (
            "Konqueror",
            vec![
                "KO",
            ],
        ),
        (
            "NetFront",
            vec![
                "3N", "NF",
            ],
        ),
        (
            "NetSurf",
            vec![
                "NE",
            ],
        ),
        (
            "Nokia Browser",
            vec![
                "DO", "NB", "NO", "NV",
            ],
        ),
        (
            "Opera",
            vec![
                "6O", "O1", "OG", "OH", "OI", "OM", "ON", "OO", "OP", "OX", "Y1",
            ],
        ),
        (
            "Safari",
            vec![
                "MF", "PV", "S7", "SF", "SO",
            ],
        ),
        (
            "Sailfish Browser",
            vec![
                "SA",
            ],
        ),
    ]
    .into_iter()
    .map(|(brand, families)| {
        (
            brand.to_owned(),
            families
                .into_iter()
                .map(|f| f.to_owned())
                .collect::<Vec<String>>(),
        )
    })
    .collect::<HashMap<String, Vec<String>>>()
}

pub fn mobile_only_browsers() -> HashSet<String> {
    [
        "0A", "0C", "0I", "0P", "0S", "18", "1M", "1N", "1W", "2E", "2F", "2M", "2N", "2P",
        "2X", "36", "3M", "3P", "4B", "4O", "4S", "5A", "5O", "5P", "6I", "6P", "7I", "7P",
        "8A", "9P", "A5", "A6", "A7", "A8", "A9", "AH", "AI", "AK", "AP", "AY", "AZ", "B0",
        "B5", "B6", "B7", "B9", "BC", "BG", "BL", "BQ", "BT", "BV", "BW", "C1", "C4", "C8",
        "CB", "CW", "D0", "D4", "D6", "DB", "DK", "DM", "DP", "DT", "DU", "EU", "EV", "EZ",
        "F0", "F3", "F4", "F6", "F7", "F8", "F9", "FG", "FK", "FM", "FR", "FT", "FX", "G2",
        "G3", "GD", "GH", "GI", "GN", "GR", "H4", "H5", "H7", "HA", "HI", "HQ", "HT", "HU",
        "HW", "I8", "I9", "IG", "II", "IO", "IS", "IV", "JB", "JR", "K2", "K4", "K7", "KA",
        "KD", "KE", "KL", "KS", "KU", "L1", "L4", "LR", "M1", "M5", "M6", "M7", "M8", "M9",
        "MF", "MM", "MN", "MR", "MZ", "N0", "N3", "N4", "N6", "N8", "N9", "NA", "NI", "NQ",
        "NX", "O4", "O6", "O8", "O9", "OC", "OI", "OL", "OM", "OU", "OZ", "P0", "P1", "P3",
        "P5", "P7", "P8", "PE", "PI", "PK", "PN", "PZ", "Q3", "QU", "RE", "RF", "RW", "S0",
        "S7", "SA", "SD", "SG", "SJ", "SK", "SM", "SQ", "ST", "SU", "T0", "T1", "T5", "TC",
        "TH", "TL", "TT", "U0", "UH", "UI", "UM", "UP", "UT", "V0", "V3", "V4", "V7", "VA",
        "VE", "VN", "VQ", "VR", "VU", "VV", "W1", "WI", "WK", "WP", "WR", "X0", "X1", "X2",
        "X3", "X4", "X5", "X6", "XB", "XN", "XO", "XT", "Y3", "YG", "YN", "YO", "YS", "Z0",
        "ZR", "ZT",
    ]
    .into_iter()
    .map(|f| f.to_owned())
    .collect::<HashSet<String>>()
}
